# Constants for mergesort comparison script
DATA_DIR = 'project/data/'
IMG_DIR = 'project/img/'
PYTHON_IMG_DIR = IMG_DIR + 'python/'
C_IMG_DIR = IMG_DIR + 'clang/'
PYTHON_CSV = DATA_DIR + 'datasheet_python.csv'
C_CSV = DATA_DIR + 'datasheet_clang.csv'
SUMMARY_CSV = DATA_DIR + 'mergesort_comparison_summary.csv'
TIME_COMPARISON_IMG = IMG_DIR + 'mergesort_time_comparison.png'
TIME_COMPARISON_PYTHON_IMG = PYTHON_IMG_DIR + 'mergesort_time_comparison_python.png'
TIME_COMPARISON_C_IMG = C_IMG_DIR + 'mergesort_time_comparison_c.png'
TIME_VS_THEORY_IMG = IMG_DIR + 'mergesort_time_vs_theory.png'
TIME_VS_THEORY_PYTHON_IMG = PYTHON_IMG_DIR + 'mergesort_time_vs_theory_python.png'
TIME_VS_THEORY_C_IMG = C_IMG_DIR + 'mergesort_time_vs_theory_c.png'
EXECSPEED_IMG = IMG_DIR + 'mergesort_execspeed_comparison.png'
EXECSPEED_PYTHON_IMG = PYTHON_IMG_DIR + 'mergesort_execspeed_comparison_python.png'
EXECSPEED_C_IMG = C_IMG_DIR + 'mergesort_execspeed_comparison_c.png'
X_LABEL = 'Input Size (N)'

# String constants
LANG_PYTHON = 'Python'
LANG_C = 'C'
COL_LANGUAGE = 'Language'
COL_INPUT_SIZE = 'InputSize'
COL_EXEC_TIME = 'ExecutionTime_ms'
COL_THEORY = 'Theoretical_nlogn'
COL_EXECSPEED = 'ExecSpeed_items_per_ms'
PLOT_TITLE_TIME = 'Merge Sort: Measured Execution Time (ms)'
PLOT_TITLE_THEORY = 'Measured Time / Theoretical n log n'
PLOT_TITLE_SPEED = 'Merge Sort: Execution Speed (items/ms)'
Y_LABEL_TIME = 'Execution Time (ms)'
Y_LABEL_THEORY = 'Time / (n log n)'
Y_LABEL_SPEED = 'Execution Speed (items/ms)'
LEGEND_LANGUAGE = 'Language'
SUMMARY_PRINT = 'Summary Table (first 10 rows):'
CHARTS_SAVED_PRINT = '\nCharts saved to project/data/. Full summary table saved as mergesort_comparison_summary.csv.'
